apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: tcp-image-to-ingress
spec:
  params:
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: dforbes-pivotal-https
    name: gitops_ssh_secret
  - default:
    - containerPort: 8080
      port: 8080
      name: http
    name: ports
  resources:
  - name: deliverable
    params:
    - name: registry
      value:
        repository: aws-tap/supply-chain
        server: harbor.donaldforbes.com
        # Add this key if you have set ca_cert_data in tap-values.yaml
        #- name: ca_cert_data
        #  value: CERT-AS-STRING
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  - name: image-provider
    params:
      - name: serviceAccount
        value: default
    templateRef:
      kind: ClusterImageTemplate
      name: image-provider-template
  - images:
    - name: image
      resource: image-provider
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: deployment-and-service-template
  - configs:
    - name: app_def
      resource: app-config
    name: apply-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: apply-bindings
  - configs:
    - name: config
      resource: apply-bindings
    name: config-writer
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        repository: aws-tap/supply-chain
        server: harbor.donaldforbes.com
        # Add this key if you have set ca_cert_data in tap-values.yaml
        #- name: ca_cert_data
        #  value: CERT-AS-STRING
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  selector:
    apps.tanzu.vmware.com/workload-type: tcp
  selectorMatchFields:
    - key: spec.image
      operator: Exists
