apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-nginx-image
  labels:
    apps.tanzu.vmware.com/workload-type: tcp
    app.kubernetes.io/part-of: tanzu-nginx-image
spec:
  params:
    - name: URL
      value: tanzu-nginx-image.donald.ingress.aws-tap.donaldforbes.com
  image: nginxinc/nginx-unprivileged
  env:
  - name: PORT
    value: 8080
