apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-nginx-image
  labels:
    apps.tanzu.vmware.com/workload-type: tcp
    app.kubernetes.io/part-of: tanzu-nginx-image
spec:
  params:
    - name: URL
      value: tanzu-nginx-image.donald.ingress.aws-tap.donaldforbes.com
  image: harbor.donaldforbes.com/apps/nginx-unprivileged@sha256:f0d7519038f4e4caf00ed112216b260226aad99284ec87cdab2030ad31a0b2f5
  env:
  - name: PORT
    value: 8080
